// Physical library API registry. Keep v1 route construction outside UI/domain components.
export const libraryEndpoints = {
  titles: '/admin/library/titles',
  title: (id: number | string) => `/admin/library/titles/${id}`,
  titleCover: (id: number | string) => `/admin/library/titles/${id}/cover`,
  titleCoverClear: (id: number | string) => `/admin/library/titles/${id}/cover/clear`,
  titleCopies: (id: number | string) => `/admin/library/titles/${id}/copies`,
  titleActivity: (id: number | string) => `/admin/library/titles/${id}/activity`,
  copies: '/admin/library/copies',
  copy: (id: number | string) => `/admin/library/copies/${id}`,
  circulations: '/admin/library/circulations',
  circulation: (id: number | string) => `/admin/library/circulations/${id}`,
  archiveTitle: (id: number | string) => `/admin/library/titles/${id}/archive`,
  copyAction: (id: number | string, action: string) => `/admin/library/copies/${id}/${action}`,
  checkout: (id: number | string) => `/admin/library/copies/${id}/checkout`,
  returnLoan: (id: number | string) => `/admin/library/circulations/${id}/return`,
  renewLoan: (id: number | string) => `/admin/library/circulations/${id}/renew`,
  recordReminder: (id: number | string) => `/admin/library/circulations/${id}/record-reminder`,
  categories: '/admin/library/categories',
  categoryHierarchy: '/admin/library/categories/hierarchy',
  category: (id: number | string) => `/admin/library/categories/${id}`,
  archiveCategory: (id: number | string) => `/admin/library/categories/${id}/archive`,
  policies: '/admin/library/policies',
  policy: (id: number | string) => `/admin/library/policies/${id}`,
  staffBorrowers: '/admin/library/borrowers/staff',
  deskLookup: '/admin/library/desk/lookup',
  requests: '/admin/library/requests',
  request: (id: number | string) => `/admin/library/requests/${id}`,
  requestReady: (id: number | string) => `/admin/library/requests/${id}/ready`,
  requestFulfill: (id: number | string) => `/admin/library/requests/${id}/fulfill`,
  requestReject: (id: number | string) => `/admin/library/requests/${id}/reject`,
  requestCancel: (id: number | string) => `/admin/library/requests/${id}/cancel`,
  overdue: '/admin/library/overdue',
  studentLoans: (id: number | string) => `/admin/library/students/${id}/loans`,
  staffLoans: (id: number | string) => `/admin/library/staff/${id}/loans`,
  inventorySessions: '/admin/library/inventory/sessions',
  inventorySession: (id: number | string) => `/admin/library/inventory/sessions/${id}`,
  inventoryStart: (id: number | string) => `/admin/library/inventory/sessions/${id}/start`,
  inventoryScan: (id: number | string) => `/admin/library/inventory/sessions/${id}/scan`,
  inventoryClose: (id: number | string) => `/admin/library/inventory/sessions/${id}/close`,
  inventoryCancel: (id: number | string) => `/admin/library/inventory/sessions/${id}/cancel`,
  labels: '/admin/library/labels',
  importPreview: '/admin/library/import/preview',
  importApply: '/admin/library/import/apply',
  analyticsSummary: '/admin/library/analytics/summary',
  analyticsCirculations: '/admin/library/analytics/circulations',
  analyticsCategories: '/admin/library/analytics/categories',
  student: {
    titles: '/student/library/titles',
    title: (id: number | string) => `/student/library/titles/${id}`,
    categories: '/student/library/categories',
    requests: '/student/library/requests',
    request: (id: number | string) => `/student/library/requests/${id}`,
    cancelRequest: (id: number | string) => `/student/library/requests/${id}/cancel`,
    loans: '/student/library/loans',
  },
} as const;
