const AR = {
  title: 'الجرس المدرسي',
  subtitle: 'اضبط أوقات الجرس والأصوات التي ستعمل تلقائيًا في المدرسة.',
  scheduleTab: 'جدول الجرس',
  audioLibraryTab: 'مكتبة الأصوات',
  defaultScheduleName: 'الجدول الرئيسي',
  deviceTitle: 'جهاز Raqeem Edge',
  noDeviceTitle: 'لم يتم ربط جهاز Raqeem Edge بهذه المدرسة بعد.',
  noDeviceDesc: 'يمكنك إعداد الجدول الآن وربط الجهاز لاحقًا.',
  agentVersion: 'إصدار Edge',
  lastSeen: 'آخر اتصال',
  neverSeen: 'لم يتصل بعد',
  revoked: 'ملغى',
  active: 'مفعّل',
  publishedTitle: 'النسخة المنشورة من الخادم',
  noPublishedVersion: 'لا توجد نسخة منشورة بعد.',
  validPeriod: 'فترة الصلاحية',
  generatedAt: 'تاريخ النشر',
  scheduleName: 'اسم الجدول',
  activationPeriod: 'فترة التفعيل',
  from: 'من',
  to: 'إلى',
  weeklyTitle: 'مواقيت الأسبوع',
  weeklyDesc: 'أضف توقيت الجرس لكل يوم واختر الصوت المناسب.',
  addTime: '+ إضافة توقيت',
  copyDay: 'نسخ هذا اليوم',
  copyHelp: 'اختر الأيام الهدف. سيتم استبدال مواقيتها الحالية بنسخة من هذا اليوم.',
  applyCopy: 'نسخ المواقيت',
  cancel: 'إلغاء',
  time: 'الوقت',
  label: 'التسمية',
  labelPlaceholder: 'مثال: بداية الدراسة',
  sound: 'الصوت',
  chooseSound: 'اختر الصوت',
  enabled: 'مفعّل',
  remove: 'حذف',
  noEvents: 'لا توجد مواقيت في هذا اليوم.',
  noAudioTitle: 'لا توجد ملفات صوتية متاحة بعد.',
  noAudioDesc: 'افتح مكتبة الأصوات واختر من أصوات رقيم أو ارفع ملف WAV للمؤسسة.',
  save: 'حفظ وتفعيل',
  saving: 'جارٍ الحفظ والتفعيل…',
  saved: 'تم حفظ جدول الجرس ونشره بنجاح. سيقوم جهاز Raqeem Edge بجلب النسخة الجديدة عند المزامنة التالية.',
  saveError: 'تعذر حفظ جدول الجرس. راجع الحقول وحاول مرة أخرى.',
  loadError: 'تعذر تحديث ملفات الجرس الصوتية.',
  nameRequired: 'اسم الجدول مطلوب.',
  rangeRequired: 'حدد تاريخ البداية والنهاية.',
  rangeOrder: 'يجب أن يكون تاريخ النهاية مساويًا أو لاحقًا لتاريخ البداية.',
  timeRequired: 'حدد وقت الجرس.',
  timeInvalid: 'أدخل الوقت بصيغة صحيحة.',
  audioRequired: 'اختر ملفًا صوتيًا.',
  duplicateTime: 'يوجد توقيت مكرر في هذا اليوم.',
  weekdays: {
    '0': 'الاثنين',
    '1': 'الثلاثاء',
    '2': 'الأربعاء',
    '3': 'الخميس',
    '4': 'الجمعة',
    '5': 'السبت',
    '6': 'الأحد',
  },
} as const;

const FR = {
  title: 'Sonnerie scolaire',
  subtitle: "Configurez les horaires et les sons qui seront exécutés automatiquement dans l’établissement.",
  scheduleTab: 'Horaire des sonneries',
  audioLibraryTab: 'Bibliothèque sonore',
  defaultScheduleName: 'Horaire principal',
  deviceTitle: 'Appareil Raqeem Edge',
  noDeviceTitle: "Aucun appareil Raqeem Edge n’est encore lié à cet établissement.",
  noDeviceDesc: "Vous pouvez préparer l’horaire maintenant et lier l’appareil plus tard.",
  agentVersion: 'Version Edge',
  lastSeen: 'Dernière connexion',
  neverSeen: 'Pas encore connecté',
  revoked: 'Révoqué',
  active: 'Actif',
  publishedTitle: 'Version publiée par le serveur',
  noPublishedVersion: 'Aucune version publiée.',
  validPeriod: 'Période de validité',
  generatedAt: 'Date de publication',
  scheduleName: "Nom de l’horaire",
  activationPeriod: "Période d’activation",
  from: 'Du',
  to: 'Au',
  weeklyTitle: 'Horaires de la semaine',
  weeklyDesc: 'Ajoutez les sonneries de chaque jour et choisissez le son correspondant.',
  addTime: '+ Ajouter un horaire',
  copyDay: 'Copier ce jour',
  copyHelp: 'Choisissez les jours cibles. Leurs horaires actuels seront remplacés par une copie de ce jour.',
  applyCopy: 'Copier les horaires',
  cancel: 'Annuler',
  time: 'Heure',
  label: 'Libellé',
  labelPlaceholder: 'Ex. Début des cours',
  sound: 'Son',
  chooseSound: 'Choisir un son',
  enabled: 'Actif',
  remove: 'Supprimer',
  noEvents: 'Aucun horaire pour ce jour.',
  noAudioTitle: 'Aucun fichier audio disponible.',
  noAudioDesc: 'Ouvrez la bibliothèque sonore pour choisir un son Raqeem ou ajouter un fichier WAV.',
  save: 'Enregistrer et activer',
  saving: 'Enregistrement et activation…',
  saved: 'L’horaire de sonnerie a été enregistré et publié. Raqeem Edge récupérera la nouvelle version lors de la prochaine synchronisation.',
  saveError: "Impossible d’enregistrer l’horaire. Vérifiez les champs puis réessayez.",
  loadError: 'Impossible de mettre à jour les sons de la sonnerie.',
  nameRequired: "Le nom de l’horaire est obligatoire.",
  rangeRequired: 'Indiquez les dates de début et de fin.',
  rangeOrder: 'La date de fin doit être égale ou postérieure à la date de début.',
  timeRequired: 'Indiquez une heure.',
  timeInvalid: 'Indiquez une heure valide.',
  audioRequired: 'Choisissez un fichier audio.',
  duplicateTime: 'Une heure est dupliquée pour ce jour.',
  weekdays: {
    '0': 'Lundi',
    '1': 'Mardi',
    '2': 'Mercredi',
    '3': 'Jeudi',
    '4': 'Vendredi',
    '5': 'Samedi',
    '6': 'Dimanche',
  },
} as const;

export type EdgeBellCopy = typeof AR | typeof FR;

export function edgeBellCopyFor(locale: string): EdgeBellCopy {
  return locale === 'fr' ? FR : AR;
}
