// @vitest-environment happy-dom
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {AttendanceForceSyncControl} from './attendance-force-sync-control';
import type {EdgeAttendanceForceSyncState,EdgeAttendanceForceSyncStatus,EdgeAttendanceSourceDevice} from '@/features/admin/edge/types';
const enqueue=vi.fn();const fetchStatus=vi.fn();const toast={show:vi.fn(),success:vi.fn(),warning:vi.fn(),error:vi.fn()};
vi.mock('@/features/admin/edge/api/attendance',()=>({enqueueAttendanceForceSync:(...a:unknown[])=>enqueue(...a),fetchAttendanceForceSyncStatus:(...a:unknown[])=>fetchStatus(...a)}));
vi.mock('@/features/i18n/locale-context',()=>({useLocale:()=>({locale:'ar'})}));
vi.mock('@/components/ui/toast',()=>({useToast:()=>toast}));
const source:EdgeAttendanceSourceDevice={id:1,source_device_id:'hik-entrance-01',vendor:'hikvision',name:'Entrance',active:true};
function status(state:EdgeAttendanceForceSyncState,o:Partial<EdgeAttendanceForceSyncStatus>={}):EdgeAttendanceForceSyncStatus{return{request_id:'fs_test',operation:'attendance.force_sync',state,source_device:{id:1,source_device_id:'hik-entrance-01',name:'Entrance',active:true},edge_device:{id:3,device_uid:'edge-1',device_name:'Edge',active:true},requested_at:'2026-10-09 12:00:00',dispatched_at:null,started_at:null,finished_at:null,expires_at:'2099-10-09 12:30:00',watermark_before:null,watermark_after:null,steps:[],events_polled:null,events_inserted:null,duplicates:null,persons_synced:null,directory_complete:null,outbox_uploaded_events:null,outbox_uploaded_directory:null,error_code:null,safe_error_message:null,...o}}
async function startWith(s:EdgeAttendanceForceSyncStatus){enqueue.mockResolvedValueOnce({success:true,data:s,meta:{}});render(<AttendanceForceSyncControl source={source}/>);fireEvent.click(screen.getByRole('button',{name:'مزامنة الآن'}));await act(async()=>{})}
beforeEach(()=>{vi.useFakeTimers();window.sessionStorage.clear();enqueue.mockReset();fetchStatus.mockReset();Object.values(toast).forEach(f=>f.mockReset())});
afterEach(()=>{cleanup();vi.useRealTimers()});
describe('AttendanceForceSyncControl',()=>{
 it('renders action for active source',()=>{render(<AttendanceForceSyncControl source={source}/>);expect(screen.getByRole('button',{name:'مزامنة الآن'})).toBeTruthy()});
 it('disables action for inactive source',()=>{render(<AttendanceForceSyncControl source={{...source,active:false}}/>);expect((screen.getByRole('button',{name:'مزامنة الآن'}) as HTMLButtonElement).disabled).toBe(true)});
 it('sends exactly one enqueue request on double click',async()=>{enqueue.mockResolvedValue({success:true,data:status('queued'),meta:{}});render(<AttendanceForceSyncControl source={source}/>);const b=screen.getByRole('button',{name:'مزامنة الآن'});fireEvent.click(b);fireEvent.click(b);await act(async()=>{});expect(enqueue).toHaveBeenCalledTimes(1);expect(enqueue).toHaveBeenCalledWith(1)});
 it.each([['queued','جارٍ بدء المزامنة…'],['dispatched','تم إرسال طلب المزامنة إلى الجهاز…'],['running','جارٍ مزامنة بيانات جهاز الحضور…']] as const)('shows %s as active',async(st,label)=>{await startWith(status(st));expect(screen.getAllByText(label).length).toBeGreaterThanOrEqual(1);expect((screen.getByRole('button',{name:label}) as HTMLButtonElement).disabled).toBe(true)});
 it('polls without re-enqueue and stops after success',async()=>{await startWith(status('queued'));fetchStatus.mockResolvedValueOnce({success:true,data:status('running'),meta:{}});await act(async()=>{vi.advanceTimersByTime(2500)});expect(fetchStatus).toHaveBeenCalledTimes(1);expect(enqueue).toHaveBeenCalledTimes(1);fetchStatus.mockResolvedValueOnce({success:true,data:status('success',{persons_synced:39,events_inserted:2,duplicates:1}),meta:{}});await act(async()=>{vi.advanceTimersByTime(2500)});expect(screen.getByText('اكتملت المزامنة بنجاح')).toBeTruthy();expect(screen.getByText(/أشخاص الدليل:/)).toBeTruthy();const n=fetchStatus.mock.calls.length;await act(async()=>{vi.advanceTimersByTime(10000)});expect(fetchStatus).toHaveBeenCalledTimes(n);expect(toast.success).toHaveBeenCalledWith('اكتملت المزامنة بنجاح')});
 it.each([['partial','اكتملت المزامنة جزئيًا','warning'],['failed','تعذرت المزامنة','error'],['expired','انتهت مهلة طلب المزامنة','warning'],['already_running','توجد مزامنة جارية بالفعل','warning'],['rejected_scope','تعذر تنفيذ المزامنة لهذا الجهاز','error']] as const)('handles terminal %s',async(st,label,tone)=>{await startWith(status(st));expect(screen.getByText(label)).toBeTruthy();expect(toast[tone]).toHaveBeenCalledWith(label)});
 it('omits counts when backend does not supply them',async()=>{await startWith(status('success'));expect(screen.queryByText(/أشخاص الدليل:/)).toBeNull();expect(screen.queryByText(/تسجيلات جديدة:/)).toBeNull()});
 it('does not enqueue again after transient status failure',async()=>{await startWith(status('queued'));fetchStatus.mockResolvedValueOnce({success:false,error:{code:'network_error',message:'offline',details:{}},meta:{}});await act(async()=>{vi.advanceTimersByTime(2500)});expect(screen.getByText(/لن تتم إعادة إرسال الطلب/)).toBeTruthy();expect(enqueue).toHaveBeenCalledTimes(1);fetchStatus.mockResolvedValueOnce({success:true,data:status('success'),meta:{}});await act(async()=>{vi.advanceTimersByTime(2500)});expect(screen.getByText('اكتملت المزامنة بنجاح')).toBeTruthy();expect(enqueue).toHaveBeenCalledTimes(1)});
 it('stops status polling after the command observation deadline',async()=>{const expiredSoon=status('queued',{expires_at:'2000-01-01 00:00:00'});await startWith(expiredSoon);await act(async()=>{vi.advanceTimersByTime(2500)});expect(screen.getByText(/توقفت متابعة الحالة/)).toBeTruthy();const n=fetchStatus.mock.calls.length;await act(async()=>{vi.advanceTimersByTime(10000)});expect(fetchStatus).toHaveBeenCalledTimes(n);expect(enqueue).toHaveBeenCalledTimes(1)});
 it('recovers an active request after refresh without enqueueing again',async()=>{window.sessionStorage.setItem('raqeem.edge.attendance.force-sync.1','fs_saved');fetchStatus.mockResolvedValueOnce({success:true,data:status('running',{request_id:'fs_saved'}),meta:{}});render(<AttendanceForceSyncControl source={source}/>);await act(async()=>{});expect(screen.getAllByText('جارٍ مزامنة بيانات جهاز الحضور…').length).toBeGreaterThanOrEqual(1);expect(enqueue).not.toHaveBeenCalled();expect(fetchStatus).toHaveBeenCalledWith('fs_saved')});
 it('shows enqueue failure and never starts polling',async()=>{enqueue.mockResolvedValueOnce({success:false,error:{code:'forbidden',message:'Forbidden',details:{}},meta:{}});render(<AttendanceForceSyncControl source={source}/>);fireEvent.click(screen.getByRole('button',{name:'مزامنة الآن'}));await act(async()=>{});expect(toast.error).toHaveBeenCalledWith('تعذر بدء المزامنة.');await act(async()=>{vi.advanceTimersByTime(10000)});expect(fetchStatus).not.toHaveBeenCalled()});
});
