'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ApiErrorView,EmptyState,LoadingState} from '@/components/states/states';
import {Badge,Card,PageHeader} from '@/components/ui/primitives';
import {useLocale} from '@/features/i18n/locale-context';
import {useToast} from '@/components/ui/toast';
import {fetchAttendanceDevicePersons,fetchAttendanceSourceDevices,fetchStaffCandidates,saveAttendancePersonMapping,unlinkAttendancePersonMapping} from '@/features/admin/edge/api/attendance';
import type {EdgeAttendanceDevicePerson,EdgeAttendanceSourceDevice,EdgeStaffCandidate} from '@/features/admin/edge/types';
import type {ApiErrorBody} from '@/types/api';
import '../edge-local-devices.css';
type Filter='all'|'mapped'|'unmapped';
const C={ar:{unavailable:'لا تتوفر لهذا الموظف علاقة مدرسية واحدة صالحة للربط بالحضور.',title:'الأجهزة المحلية',sub:'اربط مستخدمي أجهزة الحضور بموظفي رقيم. تشغيل الحضور المباشر مستقل عن الربط.',total:'مستخدمو الجهاز',mapped:'مرتبط',unmapped:'غير مرتبط',all:'الكل',search:'البحث بالاسم أو المعرّف',synced:'الدليل متزامن',off:'الحضور المباشر غير مفعّل',on:'الحضور المباشر مفعّل',link:'ربط بموظف',id:'معرّف الجهاز',inactive:'غير نشط على الجهاز',choose:'اختر موظف رقيم',staff:'ابحث باسم فرد من الطاقم بالعربية أو الفرنسية',none:'لا توجد نتائج مطابقة للبحث.',staffEmpty:'لا يوجد أفراد طاقم متاحون.',staffLoading:'جارٍ تحميل لائحة الطاقم…',clearSearch:'مسح البحث',cancel:'إلغاء',confirm:'تأكيد الربط',help:'سيصبح هذا الربط الهوية الدائمة لهذا المستخدم في جهاز الحضور.',saved:'تم حفظ الربط.',fail:'تعذر حفظ الربط.',unlink:'فك الارتباط',unlinkTitle:'تأكيد فك الارتباط',unlinkHelp:'سيتم فك الربط بين شخص الجهاز والموظف في رقيم. لن يتم حذف الموظف أو الشخص من جهاز الحضور.',unlinkConfirm:'فك الارتباط',unlinked:'تم فك الارتباط.',unlinkFail:'تعذر فك الارتباط.',noSource:'لا يوجد جهاز حضور مسجل.'},fr:{unavailable:"Ce membre ne dispose pas d’une relation scolaire unique disponible pour l’association de présence.",title:'Appareils locaux',sub:"Associez les utilisateurs des appareils de présence au personnel Raqeem. Le pointage en direct reste indépendant.",total:'Utilisateurs',mapped:'Associés',unmapped:'Non associés',all:'Tous',search:'Nom ou identifiant',synced:'Répertoire synchronisé',off:'Pointage en direct non activé',on:'Pointage en direct activé',link:'Associer',id:'Identifiant appareil',inactive:"Inactif sur l’appareil",choose:'Choisir un membre du personnel',staff:'Rechercher un membre du personnel en arabe ou en français',none:'Aucun résultat correspondant.',staffEmpty:'Aucun membre du personnel disponible.',staffLoading:'Chargement du personnel…',clearSearch:'Effacer la recherche',cancel:'Annuler',confirm:"Confirmer l’association",help:"Cette association devient l’identité persistante de cet utilisateur.",saved:'Association enregistrée.',fail:"Impossible d’enregistrer.",unlink:"Dissocier",unlinkTitle:"Confirmer la dissociation",unlinkHelp:"L’association entre l’utilisateur de l’appareil et le membre du personnel Raqeem sera retirée. Ni le membre du personnel ni l’utilisateur de l’appareil ne sera supprimé.",unlinkConfirm:"Dissocier",unlinked:"Association retirée.",unlinkFail:"Impossible de dissocier.",noSource:'Aucun appareil de présence enregistré.'}} as const;
export function LocalDeviceStaffMappingPage(){const{locale}=useLocale();const c=locale==='fr'?C.fr:C.ar;const toast=useToast();const[sources,setSources]=useState<EdgeAttendanceSourceDevice[]>([]);const[sourceId,setSourceId]=useState<number|null>(null);const[persons,setPersons]=useState<EdgeAttendanceDevicePerson[]>([]);const[error,setError]=useState<ApiErrorBody|null>(null);const[loading,setLoading]=useState(true);const[filter,setFilter]=useState<Filter>('all');const[q,setQ]=useState('');const[person,setPerson]=useState<EdgeAttendanceDevicePerson|null>(null);const[sq,setSq]=useState('');const[staff,setStaff]=useState<EdgeStaffCandidate[]>([]);const[staffLoading,setStaffLoading]=useState(false);const[selected,setSelected]=useState<EdgeStaffCandidate|null>(null);const[saving,setSaving]=useState(false);const[unlinkPerson,setUnlinkPerson]=useState<EdgeAttendanceDevicePerson|null>(null);const[unlinking,setUnlinking]=useState(false);
const loadPersons=useCallback(async(id:number)=>{const r=await fetchAttendanceDevicePersons(id);if(!r.success){setError(r.error);return;}setPersons(r.data);setError(null)},[]);
const load=useCallback(async()=>{setLoading(true);const r=await fetchAttendanceSourceDevices();if(!r.success){setError(r.error);setLoading(false);return}const s=r.data;setSources(s);const id=s[0]?.id??null;setSourceId(id);if(id)await loadPersons(id);setLoading(false)},[loadPersons]);useEffect(()=>{void load()},[load]);
useEffect(()=>{if(!person){setStaff([]);setStaffLoading(false);return}setStaffLoading(true);const t=window.setTimeout(async()=>{const r=await fetchStaffCandidates(sq);setStaff(r.success?r.data:[]);setStaffLoading(false)},sq.trim()?180:0);return()=>window.clearTimeout(t)},[person,sq]);
const source=sources.find(s=>s.id===sourceId);const counts=useMemo(()=>{const mapped=persons.filter(p=>p.mapping_status==='mapped').length;return{total:persons.length,mapped,unmapped:persons.length-mapped}},[persons]);const visible=useMemo(()=>persons.filter(p=>{const m=p.mapping_status==='mapped';if(filter==='mapped'&&!m||filter==='unmapped'&&m)return false;const x=q.trim().toLowerCase();return!x||(p.display_label??p.device_person_label??'').toLowerCase().includes(x)||p.external_person_id.toLowerCase().includes(x)}),[persons,filter,q]);
async function save(){if(!sourceId||!person||!selected||selected.staff_relationship_id==null||saving)return;setSaving(true);const r=await saveAttendancePersonMapping(sourceId,person.external_person_id,selected.staff_relationship_id,person.display_label??person.device_person_label??undefined);setSaving(false);if(!r.success){toast.error(c.fail);return}toast.success(c.saved);setPerson(null);setSelected(null);await loadPersons(sourceId)}
async function unlink(){if(!sourceId||!unlinkPerson||unlinking)return;setUnlinking(true);const r=await unlinkAttendancePersonMapping(sourceId,unlinkPerson.external_person_id);setUnlinking(false);if(!r.success){toast.error(c.unlinkFail);return}toast.success(c.unlinked);setUnlinkPerson(null);await loadPersons(sourceId)}
if(loading)return <LoadingState/>;if(error)return <ApiErrorView error={error} onRetry={()=>void load()}/>;
return <div className="admin-workspace edge-local-devices"><PageHeader title={c.title} subtitle={c.sub}/>{!source?<EmptyState icon="◫" title={c.noSource}/>:<><div className="edge-device-selector"><label><span>{c.title}</span><select className="input" value={sourceId??''} onChange={async e=>{const id=Number(e.target.value);setSourceId(id);await loadPersons(id)}}>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="edge-device-semantic-status"><Badge tone="green">{c.synced}</Badge><Badge tone={source.active?'green':'amber'}>{source.active?c.on:c.off}</Badge></div></div><div className="edge-mapping-summary"><Card><strong>{counts.total}</strong><span>{c.total}</span></Card><Card><strong>{counts.mapped}</strong><span>{c.mapped}</span></Card><Card><strong>{counts.unmapped}</strong><span>{c.unmapped}</span></Card></div><div className="edge-mapping-toolbar"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder={c.search}/><div className="edge-filter-group">{(['all','unmapped','mapped'] as Filter[]).map(f=><button key={f} type="button" className={filter===f?'is-active':''} onClick={()=>setFilter(f)}>{c[f]}</button>)}</div></div><div className="edge-person-list">{visible.map(p=><Card key={p.external_person_id} className="edge-person-card"><div className="edge-person-identity"><div className="edge-avatar">{(p.display_label??p.device_person_label??'').trim()[0]||'?'}</div><div><strong dir="auto">{p.display_label??p.device_person_label??p.external_person_id}</strong><span>{c.id}: <bdi dir="ltr">{p.external_person_id}</bdi></span></div></div><div className="edge-person-state">{p.device_user_active===false?<Badge tone="amber">{c.inactive}</Badge>:null}<Badge tone={p.mapping_status==='mapped'?'green':'amber'}>{p.mapping_status==='mapped'?c.mapped:c.unmapped}</Badge>{p.mapping_status==='mapped'?<span dir="auto">{p.staff?.display_name||p.staff_relationship_id}</span>:null}</div>{p.mapping_status!=='mapped'?<button className="btn btn--primary btn--sm" type="button" onClick={()=>{setPerson(p);setSq('');setStaff([]);setSelected(null)}}>{c.link}</button>:<button className="btn btn--ghost btn--sm" type="button" onClick={()=>setUnlinkPerson(p)}>{c.unlink}</button>}</Card>)}</div></>}
{unlinkPerson?<div className="edge-mapping-backdrop"><section className="edge-mapping-dialog" role="dialog" aria-modal="true"><header><div><h2>{c.unlinkTitle}</h2><p><strong dir="auto">{unlinkPerson.display_label??unlinkPerson.device_person_label??unlinkPerson.external_person_id}</strong> · <bdi dir="ltr">{unlinkPerson.external_person_id}</bdi></p></div></header><div><p>{c.unlinkHelp}</p><strong dir="auto">{unlinkPerson.display_label??unlinkPerson.device_person_label??unlinkPerson.external_person_id} → {unlinkPerson.staff?.display_name||unlinkPerson.staff_relationship_id}</strong></div><footer><button className="btn btn--ghost" type="button" disabled={unlinking} onClick={()=>setUnlinkPerson(null)}>{c.cancel}</button><button className="btn btn--primary" type="button" disabled={unlinking} onClick={()=>void unlink()}>{c.unlinkConfirm}</button></footer></section></div>:null}
{person?<div className="edge-mapping-backdrop"><section className="edge-mapping-dialog" role="dialog" aria-modal="true"><header><div><h2>{c.choose}</h2><p><strong dir="auto">{person.display_label??person.device_person_label??person.external_person_id}</strong> · <bdi dir="ltr">{person.external_person_id}</bdi></p></div></header>{!selected?<><div className="edge-staff-search"><input autoFocus className="input" value={sq} onChange={e=>setSq(e.target.value)} placeholder={c.staff}/>{sq?<button type="button" className="btn btn--ghost btn--sm" onClick={()=>setSq('')} aria-label={c.clearSearch}>×</button>:null}</div>{staffLoading?<p className="edge-no-staff">{c.staffLoading}</p>:<div className="edge-staff-results">{staff.map(s=>{const ar=typeof s.name_ar==='string'?s.name_ar.trim():'';const fr=typeof s.name_fr==='string'?s.name_fr.trim():'';const primary=ar||fr||s.name;const secondary=fr&&fr.toLocaleLowerCase()!==primary.trim().toLocaleLowerCase()?fr:(!ar&&s.name&&s.name.toLocaleLowerCase()!==primary.toLocaleLowerCase()?s.name:'');return <button key={s.staff_relationship_id??s.id} type="button" disabled={s.staff_relationship_id==null} onClick={()=>setSelected(s)}><span className="edge-staff-avatar">{primary.trim()[0]||'?'}</span><span className="edge-staff-copy"><strong dir="auto">{primary}</strong>{secondary?<span dir="auto">{secondary}</span>:null}<small>{s.staff_relationship_id==null?c.unavailable:(s.role_display_name||s.job_title||'')}</small></span></button>})}</div>}{!staffLoading&&staff.length===0?<p className="edge-no-staff">{sq.trim()?c.none:c.staffEmpty}</p>:null}</>:<div><p>{c.help}</p><strong dir="auto">{person.display_label??person.device_person_label??person.external_person_id} → {selected.name_ar||selected.name}</strong>{selected.staff_relationship_id==null?<p className="edge-no-staff">{c.unavailable}</p>:null}</div>}<footer><button className="btn btn--ghost" type="button" disabled={saving} onClick={()=>{if(selected)setSelected(null);else setPerson(null)}}>{c.cancel}</button>{selected?<button className="btn btn--primary" type="button" disabled={saving||selected.staff_relationship_id==null} onClick={()=>void save()}>{c.confirm}</button>:null}</footer></section></div>:null}</div>}
