'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ApiErrorView,EmptyState,LoadingState} from '@/components/states/states';
import {Badge,Card,PageHeader} from '@/components/ui/primitives';
import {useLocale} from '@/features/i18n/locale-context';
import {useToast} from '@/components/ui/toast';
import {fetchAttendanceDevicePersons,fetchAttendanceSourceDevices,fetchStaffCandidates,saveAttendancePersonMapping} from '@/features/admin/edge/api/attendance';
import type {EdgeAttendanceDevicePerson,EdgeAttendanceSourceDevice,EdgeStaffCandidate} from '@/features/admin/edge/types';
import type {ApiErrorBody} from '@/types/api';
import type {StaffMember} from '@/types/academic-setup';
import '../edge-local-devices.css';
type Filter='all'|'mapped'|'unmapped';
const C={ar:{title:'الأجهزة المحلية',sub:'اربط مستخدمي أجهزة الحضور بموظفي رقيم. تشغيل الحضور المباشر مستقل عن الربط.',total:'مستخدمو الجهاز',mapped:'مرتبط',unmapped:'غير مرتبط',all:'الكل',search:'البحث بالاسم أو المعرّف',synced:'الدليل متزامن',off:'الحضور المباشر غير مفعّل',on:'الحضور المباشر مفعّل',link:'ربط بموظف',id:'معرّف الجهاز',inactive:'غير نشط على الجهاز',choose:'اختر موظف رقيم',staff:'ابحث باسم الموظف بالعربية أو الفرنسية',none:'لا يوجد موظف مطابق. يمكن ترك المستخدم غير مرتبط.',cancel:'إلغاء',confirm:'تأكيد الربط',help:'سيصبح هذا الربط الهوية الدائمة لهذا المستخدم في جهاز الحضور.',saved:'تم حفظ الربط.',fail:'تعذر حفظ الربط.',noSource:'لا يوجد جهاز حضور مسجل.'},fr:{title:'Appareils locaux',sub:"Associez les utilisateurs des appareils de présence au personnel Raqeem. Le pointage en direct reste indépendant.",total:'Utilisateurs',mapped:'Associés',unmapped:'Non associés',all:'Tous',search:'Nom ou identifiant',synced:'Répertoire synchronisé',off:'Pointage en direct non activé',on:'Pointage en direct activé',link:'Associer',id:'Identifiant appareil',inactive:"Inactif sur l’appareil",choose:'Choisir un membre du personnel',staff:'Rechercher en arabe ou en français',none:'Aucun membre correspondant. Vous pouvez laisser cet utilisateur non associé.',cancel:'Annuler',confirm:"Confirmer l’association",help:"Cette association devient l’identité persistante de cet utilisateur.",saved:'Association enregistrée.',fail:"Impossible d’enregistrer.",noSource:'Aucun appareil de présence enregistré.'}} as const;
const candidate=(m:StaffMember):EdgeStaffCandidate=>({id:m.id,name:m.display_name||m.name,name_ar:m.name_ar,name_fr:m.name_fr,role_display_name:m.role_display_name,job_title:m.job_title,active:m.active,status:m.status});
export function LocalDeviceStaffMappingPage(){const{locale}=useLocale();const c=locale==='fr'?C.fr:C.ar;const toast=useToast();const[sources,setSources]=useState<EdgeAttendanceSourceDevice[]>([]);const[sourceId,setSourceId]=useState<number|null>(null);const[persons,setPersons]=useState<EdgeAttendanceDevicePerson[]>([]);const[error,setError]=useState<ApiErrorBody|null>(null);const[loading,setLoading]=useState(true);const[filter,setFilter]=useState<Filter>('all');const[q,setQ]=useState('');const[person,setPerson]=useState<EdgeAttendanceDevicePerson|null>(null);const[sq,setSq]=useState('');const[staff,setStaff]=useState<EdgeStaffCandidate[]>([]);const[selected,setSelected]=useState<EdgeStaffCandidate|null>(null);const[saving,setSaving]=useState(false);
const loadPersons=useCallback(async(id:number)=>{const r=await fetchAttendanceDevicePersons(id);if(!r.success){setError(r.error);return;}setPersons(r.data.persons??[]);setError(null)},[]);
const load=useCallback(async()=>{setLoading(true);const r=await fetchAttendanceSourceDevices();if(!r.success){setError(r.error);setLoading(false);return}const s=r.data.source_devices??[];setSources(s);const id=s[0]?.id??null;setSourceId(id);if(id)await loadPersons(id);setLoading(false)},[loadPersons]);useEffect(()=>{void load()},[load]);
useEffect(()=>{if(!person||sq.trim().length<2){setStaff([]);return}const t=window.setTimeout(async()=>{const r=await fetchStaffCandidates({search:sq.trim(),status:'active',page:1,page_size:20});setStaff(r.success?r.data.map(candidate):[])},250);return()=>clearTimeout(t)},[person,sq]);
const source=sources.find(s=>s.id===sourceId);const counts=useMemo(()=>{const mapped=persons.filter(p=>p.mapping?.active).length;return{total:persons.length,mapped,unmapped:persons.length-mapped}},[persons]);const visible=useMemo(()=>persons.filter(p=>{const m=!!p.mapping?.active;if(filter==='mapped'&&!m||filter==='unmapped'&&m)return false;const x=q.trim().toLowerCase();return!x||p.display_label.toLowerCase().includes(x)||p.external_person_id.toLowerCase().includes(x)}),[persons,filter,q]);
async function save(){if(!sourceId||!person||!selected||saving)return;setSaving(true);const r=await saveAttendancePersonMapping(sourceId,person.external_person_id,selected.id,person.display_label);setSaving(false);if(!r.success){toast.error(c.fail);return}toast.success(c.saved);setPerson(null);setSelected(null);await loadPersons(sourceId)}
if(loading)return <LoadingState/>;if(error)return <ApiErrorView error={error} onRetry={()=>void load()}/>;
return <div className="admin-workspace edge-local-devices"><PageHeader title={c.title} subtitle={c.sub}/>{!source?<EmptyState icon="◫" title={c.noSource}/>:<><div className="edge-device-selector"><label><span>{c.title}</span><select className="input" value={sourceId??''} onChange={async e=>{const id=Number(e.target.value);setSourceId(id);await loadPersons(id)}}>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="edge-device-semantic-status"><Badge tone="green">{c.synced}</Badge><Badge tone={source.active?'green':'amber'}>{source.active?c.on:c.off}</Badge></div></div><div className="edge-mapping-summary"><Card><strong>{counts.total}</strong><span>{c.total}</span></Card><Card><strong>{counts.mapped}</strong><span>{c.mapped}</span></Card><Card><strong>{counts.unmapped}</strong><span>{c.unmapped}</span></Card></div><div className="edge-mapping-toolbar"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder={c.search}/><div className="edge-filter-group">{(['all','unmapped','mapped'] as Filter[]).map(f=><button key={f} type="button" className={filter===f?'is-active':''} onClick={()=>setFilter(f)}>{c[f]}</button>)}</div></div><div className="edge-person-list">{visible.map(p=><Card key={p.external_person_id} className="edge-person-card"><div className="edge-person-identity"><div className="edge-avatar">{p.display_label.trim()[0]||'?'}</div><div><strong dir="auto">{p.display_label}</strong><span>{c.id}: <bdi dir="ltr">{p.external_person_id}</bdi></span></div></div><div className="edge-person-state">{p.device_user_active===false||p.device_user_active_state==='inactive'?<Badge tone="amber">{c.inactive}</Badge>:null}<Badge tone={p.mapping?.active?'green':'amber'}>{p.mapping?.active?c.mapped:c.unmapped}</Badge>{p.mapping?.active?<span dir="auto">{p.mapping.staff_name_ar||p.mapping.staff_name_fr||p.mapping.staff_name||p.mapping.staff_relationship_id}</span>:null}</div>{!p.mapping?.active?<button className="btn btn--primary btn--sm" type="button" onClick={()=>{setPerson(p);setSq('');setStaff([]);setSelected(null)}}>{c.link}</button>:null}</Card>)}</div></>}
{person?<div className="edge-mapping-backdrop"><section className="edge-mapping-dialog" role="dialog" aria-modal="true"><header><div><h2>{c.choose}</h2><p><strong dir="auto">{person.display_label}</strong> · <bdi dir="ltr">{person.external_person_id}</bdi></p></div></header>{!selected?<><input autoFocus className="input" value={sq} onChange={e=>setSq(e.target.value)} placeholder={c.staff}/><div className="edge-staff-results">{staff.map(s=><button key={s.id} type="button" onClick={()=>setSelected(s)}><strong dir="auto">{s.name_ar||s.name}</strong>{s.name_fr?<span>{s.name_fr}</span>:null}<small>{s.role_display_name||s.job_title||''}</small></button>)}</div>{sq.trim().length>=2&&staff.length===0?<p className="edge-no-staff">{c.none}</p>:null}</>:<div><p>{c.help}</p><strong dir="auto">{person.display_label} → {selected.name_ar||selected.name}</strong></div>}<footer><button className="btn btn--ghost" type="button" disabled={saving} onClick={()=>{if(selected)setSelected(null);else setPerson(null)}}>{c.cancel}</button>{selected?<button className="btn btn--primary" type="button" disabled={saving} onClick={()=>void save()}>{c.confirm}</button>:null}</footer></section></div>:null}</div>}
