import type { Locale } from '@/lib/i18n/config';

const COPY: Record<Locale, Record<string, string>> = {
  ar: {
    title: 'تسجيل تلميذ جديد',
    subtitle: 'صفحة واحدة للتسجيل الكامل؛ يبني رقيم المسار المالي والتشغيلي تلقائيًا.',
    academic: 'المسار الدراسي',
    school: 'المؤسسة',
    year: 'السنة الدراسية',
    cycle: 'السلك',
    level: 'المستوى',
    enrollmentDate: 'تاريخ الالتحاق',
    classAuto: 'القسم يحدد تلقائيًا بعد التسجيل',
    student: 'المعلومات الشخصية',
    firstNameAr: 'الاسم الشخصي بالعربية',
    lastNameAr: 'الاسم العائلي بالعربية',
    firstNameFr: 'الاسم الشخصي بالفرنسية',
    lastNameFr: 'الاسم العائلي بالفرنسية',
    gender: 'الجنس',
    dob: 'تاريخ الازدياد',
    previousSchool: 'المدرسة السابقة',
    address: 'العنوان',
    family: 'وضع الأسرة',
    parentsTogether: 'الوالدان معًا',
    separated: 'منفصلان / مطلقان',
    singleGuardian: 'ولي واحد',
    guardianship: 'وصاية / كفالة',
    special: 'حالة خاصة',
    guardians: 'أولياء الأمر',
    father: 'الأب',
    mother: 'الأم',
    guardian: 'الولي / الوصي',
    newGuardian: 'ولي جديد',
    existingGuardian: 'ولي موجود',
    nameAr: 'الاسم بالعربية',
    nameFr: 'الاسم بالفرنسية',
    preferredLanguage: 'اللغة المفضلة',
    arabic: 'العربية',
    french: 'الفرنسية',
    phone: 'الهاتف',
    addPhone: 'إضافة رقم هاتف',
    savePhone: 'حفظ رقم الهاتف',
    phoneUpdated: 'تم حفظ رقم الهاتف.',
    phoneUpdateFailed: 'تعذر حفظ رقم الهاتف.',
    identity: 'رقم الهوية (اختياري)',
    search: 'ابحث بالاسم أو الهاتف',
    searching: 'جارٍ البحث…',
    noMatches: 'لا توجد نتائج مطابقة.',
    useGuardian: 'استخدام هذا الولي',
    linked: 'مضاف',
    change: 'تغيير',
    rights: 'صلاحيات هذا الولي',
    legal: 'مسؤول قانوني',
    financial: 'مسؤول الأداء',
    pickup: 'مسموح له باستلام التلميذ',
    services: 'الخدمات الاختيارية',
    servicesLead: 'الرسوم الأساسية تطبق تلقائيًا. اختر فقط الخدمات الإضافية المطلوبة.',
    noServices: 'لا توجد خدمات اختيارية مؤهلة لهذا المستوى.',
    loadingServices: 'جارٍ تحميل الخدمات المؤهلة…',
    adjust: 'تعديل السعر والفترة',
    adjustTitle: 'تعديل السعر والفترة',
    item: 'البند',
    price: 'السعر',
    from: 'من شهر',
    to: 'إلى شهر',
    reason: 'سبب التعديل',
    save: 'حفظ',
    cancel: 'إلغاء',
    summary: 'ملخص التسجيل',
    payer: 'ولي الأداء',
    selectedServices: 'الخدمات',
    monthlyTotal: 'المجموع الشهري',
    oneTimeTotal: 'المبالغ لمرة واحدة',
    none: 'بدون خدمات إضافية',
    submit: 'تسجيل التلميذ',
    saving: 'جارٍ تسجيل التلميذ…',
    successTitle: 'تم تسجيل التلميذ بنجاح',
    successLead: 'تم إعداد الرسوم والاستحقاقات تلقائيًا.',
    assignedClass: 'القسم',
    pendingClass: 'يحتاج توزيعًا',
    openStudent: 'فتح ملف التلميذ',
    registerAnother: 'تسجيل تلميذ آخر',
    collectNow: 'تحصيل الآن',
    optionsFailed: 'تعذر تحميل خيارات التسجيل. أعد المحاولة.',
    planMissing: 'إعداد الرسوم لهذا المستوى غير مكتمل.',
    planAmbiguous: 'توجد أكثر من خطة مؤهلة؛ يلزم تصحيح إعداد الرسوم.',
    guardianDuplicate: 'تم العثور على ولي مطابق. استخدم السجل الموجود بدل إنشاء سجل جديد.',
    billingAmbiguous: 'يرجى تحديد مسؤول الأداء.',
    accountFailed: 'تعذر إكمال حساب ولي الأمر؛ لم يتم حفظ التسجيل.',
    serviceUnavailable: 'إحدى الخدمات المختارة لم تعد متاحة لهذا المستوى.',
    genericError: 'تعذر إكمال التسجيل. لم يتم حفظ تسجيل جزئي.',
    requiredError: 'راجع الحقول المطلوبة قبل التسجيل.',
    specialLegalError: 'حدد وليًا واحدًا على الأقل كمسؤول قانوني.',
    specialBillingError: 'حدد وليًا واحدًا على الأقل كمسؤول عن الأداء.',
    pricingReasonError: 'أدخل سبب تعديل السعر أو الفترة.',
    retry: 'إعادة المحاولة',
    select: 'اختر',
  },
  en: {
    title: 'Register a new student', subtitle: 'One-page full registration; Raqeem builds the operational and financial setup automatically.', academic: 'Academic path', school: 'School', year: 'Academic year', cycle: 'Cycle', level: 'Level', enrollmentDate: 'Joining date', classAuto: 'Class is assigned automatically after registration', student: 'Student information', firstNameAr: 'First name in Arabic', lastNameAr: 'Last name in Arabic', firstNameFr: 'First name in French', lastNameFr: 'Last name in French', gender: 'Gender', dob: 'Date of birth', previousSchool: 'Previous school', address: 'Address', family: 'Family situation', parentsTogether: 'Parents together', separated: 'Separated / divorced', singleGuardian: 'Single guardian', guardianship: 'Guardianship', special: 'Special case', guardians: 'Guardians', father: 'Father', mother: 'Mother', guardian: 'Guardian', newGuardian: 'New guardian', existingGuardian: 'Existing guardian', nameAr: 'Name in Arabic', nameFr: 'Name in French', preferredLanguage: 'Preferred language', arabic: 'Arabic', french: 'French', phone: 'Phone', addPhone: 'Add phone number', savePhone: 'Save phone number', phoneUpdated: 'Phone number saved.', phoneUpdateFailed: 'Could not save the phone number.', identity: 'Identity number (optional)', search: 'Search by name or phone', searching: 'Searching…', noMatches: 'No matching results.', useGuardian: 'Use this guardian', linked: 'Added', change: 'Change', rights: 'Guardian permissions', legal: 'Legal guardian', financial: 'Billing responsible', pickup: 'Authorized pickup', services: 'Optional services', servicesLead: 'Core fees are applied automatically. Select only the optional services requested.', noServices: 'No eligible optional services for this level.', loadingServices: 'Loading eligible services…', adjust: 'Adjust price and period', adjustTitle: 'Adjust price and period', item: 'Item', price: 'Price', from: 'From month', to: 'To month', reason: 'Reason', save: 'Save', cancel: 'Cancel', summary: 'Registration summary', payer: 'Billing guardian', selectedServices: 'Services', monthlyTotal: 'Monthly total', oneTimeTotal: 'One-time amounts', none: 'No optional services', submit: 'Register student', saving: 'Registering student…', successTitle: 'Student registered successfully', successLead: 'Fees and instalments were prepared automatically.', assignedClass: 'Class', pendingClass: 'Needs distribution', openStudent: 'Open student profile', registerAnother: 'Register another student', collectNow: 'Collect now', optionsFailed: 'Could not load registration options. Try again.', planMissing: 'Fee setup for this level is incomplete.', planAmbiguous: 'More than one eligible plan exists; fee setup must be corrected.', guardianDuplicate: 'A matching guardian was found. Use the existing record instead of creating a duplicate.', billingAmbiguous: 'Choose the billing responsible guardian.', accountFailed: 'Guardian account setup failed; registration was not saved.', serviceUnavailable: 'A selected service is no longer eligible for this level.', genericError: 'Registration could not be completed. No partial registration was saved.', requiredError: 'Review the required fields before registering.', specialLegalError: 'Choose at least one legal guardian.', specialBillingError: 'Choose at least one billing responsible guardian.', pricingReasonError: 'Enter a reason for the price or period change.', retry: 'Retry', select: 'Select',
  },
  fr: {
    title: 'Inscrire un nouvel élève', subtitle: 'Inscription complète sur une seule page ; Raqeem construit automatiquement la structure opérationnelle et financière.', academic: 'Parcours scolaire', school: 'Établissement', year: 'Année scolaire', cycle: 'Cycle', level: 'Niveau', enrollmentDate: "Date d'entrée", classAuto: 'La classe est attribuée automatiquement après l’inscription', student: 'Informations de l’élève', firstNameAr: 'Prénom en arabe', lastNameAr: 'Nom en arabe', firstNameFr: 'Prénom en français', lastNameFr: 'Nom en français', gender: 'Sexe', dob: 'Date de naissance', previousSchool: 'École précédente', address: 'Adresse', family: 'Situation familiale', parentsTogether: 'Parents ensemble', separated: 'Séparés / divorcés', singleGuardian: 'Un seul responsable', guardianship: 'Tutelle / kafala', special: 'Cas particulier', guardians: 'Responsables', father: 'Père', mother: 'Mère', guardian: 'Responsable / tuteur', newGuardian: 'Nouveau responsable', existingGuardian: 'Responsable existant', nameAr: 'Nom en arabe', nameFr: 'Nom en français', preferredLanguage: 'Langue préférée', arabic: 'Arabe', french: 'Français', phone: 'Téléphone', addPhone: 'Ajouter un numéro', savePhone: 'Enregistrer le numéro', phoneUpdated: 'Numéro enregistré.', phoneUpdateFailed: 'Impossible d’enregistrer le numéro.', identity: "Numéro d’identité (facultatif)", search: 'Rechercher par nom ou téléphone', searching: 'Recherche…', noMatches: 'Aucun résultat.', useGuardian: 'Utiliser ce responsable', linked: 'Ajouté', change: 'Changer', rights: 'Autorisations de ce responsable', legal: 'Responsable légal', financial: 'Responsable du paiement', pickup: 'Autorisé à récupérer l’élève', services: 'Services optionnels', servicesLead: 'Les frais de base sont appliqués automatiquement. Sélectionnez uniquement les services supplémentaires.', noServices: 'Aucun service optionnel éligible pour ce niveau.', loadingServices: 'Chargement des services éligibles…', adjust: 'Modifier le prix et la période', adjustTitle: 'Modifier le prix et la période', item: 'Élément', price: 'Prix', from: 'Du mois', to: 'Au mois', reason: 'Motif', save: 'Enregistrer', cancel: 'Annuler', summary: 'Résumé de l’inscription', payer: 'Responsable du paiement', selectedServices: 'Services', monthlyTotal: 'Total mensuel', oneTimeTotal: 'Montants uniques', none: 'Aucun service optionnel', submit: 'Inscrire l’élève', saving: 'Inscription en cours…', successTitle: 'Élève inscrit avec succès', successLead: 'Les frais et échéances ont été préparés automatiquement.', assignedClass: 'Classe', pendingClass: 'À répartir', openStudent: 'Ouvrir le dossier', registerAnother: 'Inscrire un autre élève', collectNow: 'Encaisser maintenant', optionsFailed: 'Impossible de charger les options d’inscription. Réessayez.', planMissing: 'La configuration des frais pour ce niveau est incomplète.', planAmbiguous: 'Plusieurs plans sont éligibles ; la configuration des frais doit être corrigée.', guardianDuplicate: 'Un responsable correspondant existe déjà. Utilisez la fiche existante.', billingAmbiguous: 'Choisissez le responsable du paiement.', accountFailed: 'La création du compte responsable a échoué ; l’inscription n’a pas été enregistrée.', serviceUnavailable: 'Un service sélectionné n’est plus disponible pour ce niveau.', genericError: 'Impossible de terminer l’inscription. Aucune inscription partielle n’a été conservée.', requiredError: 'Vérifiez les champs obligatoires avant l’inscription.', specialLegalError: 'Choisissez au moins un responsable légal.', specialBillingError: 'Choisissez au moins un responsable du paiement.', pricingReasonError: 'Indiquez le motif de la modification du prix ou de la période.', retry: 'Réessayer', select: 'Choisir',
  },
  es: {
    title: 'Registrar un alumno', subtitle: 'Inscripción completa en una sola página; Raqeem prepara automáticamente la estructura operativa y financiera.', academic: 'Trayectoria académica', school: 'Centro', year: 'Año académico', cycle: 'Ciclo', level: 'Nivel', enrollmentDate: 'Fecha de incorporación', classAuto: 'La clase se asigna automáticamente después del registro', student: 'Información del alumno', firstNameAr: 'Nombre en árabe', lastNameAr: 'Apellido en árabe', firstNameFr: 'Nombre en francés', lastNameFr: 'Apellido en francés', gender: 'Sexo', dob: 'Fecha de nacimiento', previousSchool: 'Centro anterior', address: 'Dirección', family: 'Situación familiar', parentsTogether: 'Padres juntos', separated: 'Separados / divorciados', singleGuardian: 'Un responsable', guardianship: 'Tutela', special: 'Caso especial', guardians: 'Responsables', father: 'Padre', mother: 'Madre', guardian: 'Tutor', newGuardian: 'Nuevo responsable', existingGuardian: 'Responsable existente', nameAr: 'Nombre en árabe', nameFr: 'Nombre en francés', preferredLanguage: 'Idioma preferido', arabic: 'Árabe', french: 'Francés', phone: 'Teléfono', addPhone: 'Añadir teléfono', savePhone: 'Guardar teléfono', phoneUpdated: 'Teléfono guardado.', phoneUpdateFailed: 'No se pudo guardar el teléfono.', identity: 'Documento (opcional)', search: 'Buscar por nombre o teléfono', searching: 'Buscando…', noMatches: 'Sin resultados.', useGuardian: 'Usar este responsable', linked: 'Añadido', change: 'Cambiar', rights: 'Permisos del responsable', legal: 'Responsable legal', financial: 'Responsable del pago', pickup: 'Autorizado para recoger al alumno', services: 'Servicios opcionales', servicesLead: 'Las cuotas básicas se aplican automáticamente. Seleccione solo los servicios adicionales.', noServices: 'No hay servicios opcionales elegibles para este nivel.', loadingServices: 'Cargando servicios elegibles…', adjust: 'Modificar precio y período', adjustTitle: 'Modificar precio y período', item: 'Concepto', price: 'Precio', from: 'Desde', to: 'Hasta', reason: 'Motivo', save: 'Guardar', cancel: 'Cancelar', summary: 'Resumen', payer: 'Responsable del pago', selectedServices: 'Servicios', monthlyTotal: 'Total mensual', oneTimeTotal: 'Importes de una sola vez', none: 'Sin servicios opcionales', submit: 'Registrar alumno', saving: 'Registrando…', successTitle: 'Alumno registrado correctamente', successLead: 'Las cuotas y vencimientos se prepararon automáticamente.', assignedClass: 'Clase', pendingClass: 'Pendiente de distribución', openStudent: 'Abrir ficha', registerAnother: 'Registrar otro alumno', collectNow: 'Cobrar ahora', optionsFailed: 'No se pudieron cargar las opciones. Inténtelo de nuevo.', planMissing: 'La configuración de cuotas para este nivel está incompleta.', planAmbiguous: 'Existe más de un plan elegible; debe corregirse la configuración.', guardianDuplicate: 'Se encontró un responsable coincidente. Use el registro existente.', billingAmbiguous: 'Seleccione el responsable del pago.', accountFailed: 'No se pudo preparar la cuenta del responsable; no se guardó el registro.', serviceUnavailable: 'Un servicio seleccionado ya no está disponible para este nivel.', genericError: 'No se pudo completar el registro. No se guardó ningún registro parcial.', requiredError: 'Revise los campos obligatorios.', specialLegalError: 'Seleccione al menos un responsable legal.', specialBillingError: 'Seleccione al menos un responsable del pago.', pricingReasonError: 'Indique el motivo del cambio de precio o período.', retry: 'Reintentar', select: 'Seleccionar',
  },
};

export function fullRegistrationCopy(locale: Locale, key: string): string {
  return COPY[locale]?.[key] ?? COPY.en[key] ?? key;
}
